/**
 * This is a class that contains all of our TOP SECRET API KEYS BE CAREFUL THIS SHIT IS SECRET AS FUCK
 */
public class Secret
{
    static final String FOURSQUARE_CLIENT_ID = "0UXKNKMOAUUDQZNUEB3FFOZ2DJXIZMNPZQS1UWZXCFFM4KNB",
    FOURSQUARE_CLIENT_SECRET = "SZTVMMSNH4EUXUWT2TF3UQBMYQJHSLEB54Z2THED5G5AI0QG",
    GOOGLE_API_KEY = "AIzaSyDuWmWpGvL_g1I5CY7nuYHRhTAyPmqeHSk",
    YELP_CONSUMER_KEY = "vOV39IxzLzAdEB204aDoNQ",
    YELP_CONSUMER_SECRET = "IquNFF6xRMBtl7lQ5Jj9qW4EcMo",
    YELP_TOKEN = "bDQRzPUiIKPUfjGuA2uprs1dAVh1IqwQ",
    YELP_TOKEN_SECRET = "0V151LHskqZrMGh4hMs0Fwy7vBs",      
    YP_KEY = "3t415tkz1w";
    static final int me = 17;    
}